import Head from "next/head";

function AppBar() {
	return (
		<Head>
			<title>Create T3 App</title>
			<meta name="description" content="Generated by create-t3-app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
	);
}

export default AppBar;
